### Testar a listagem de produtos (GET)
GET http://localhost:3000/produtos

###

### Testar a adição de um novo produto (POST)
POST http://localhost:3000/produtos
Content-Type: application/json

{
  "nome": "Bibimbap",
  "preco": 35.50
}

###

### Testar a remoção de um produto (DELETE)
DELETE http://localhost:3000/produtos/1